openapi: 3.0.3
info:
  title: "Test drive interface for e-Prescription FdV Module"
  description: "REST interface to automate the test of a e-Prescription FdV Module implementation."
  version: 2.0.0
  contact:
    name: gematik GmbH
    email: software-development@gematik.de
    url: https://www.gematik.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://localhost:443
    variables: { }
    description: ERP Modul Testinterface

tags:
  - name: Info
    description: "Information about test driver interface and Test-FdV"
  - name: Login
    description: "Operations to login with eID or smart card"
  - name: E-Prescription
    description: "Operations for retrieving, deleting and patching e-prescriptions"
  - name: Dispensing information
    description: "Retrieve a list of medication dispenses"
  - name: Audit Events
    description: "Retrieve a list of audit events"
  - name: Pharmacy
    description: "Assigning an e-prescription to a pharmacy and searching for a pharmacy based on certain parameters"
  - name: Consent
    description: "Operations to create, delete or retrieve a consent for a patient by category"
  - name: EU-Prescription
    description: "Operations to redeem e-prescriptions in other EU countries"

paths:
  /erp/testdriver/api/v1/info:
    get:
      summary: "General information about this test driver interface and the test FdV"
      tags:
        - Info
      responses:
        200:
          $ref: "./v1-commons.yaml#/components/responses/TestDriverInfo"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestDriverError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/start:
    put:
      summary: "Start die Test-FdV"
      tags:
        - Info
      responses:
        200:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestDriverError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/stop:
    put:
      summary: "Stop die Test-FdV"
      tags:
        - Info
      responses:
        200:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestDriverError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/login:
    put:
      summary: "Operation to login with an kvnr"
      tags:
        - Login
      requestBody:
        $ref: "./v1-commons.yaml#/components/requestBodies/Login"
      responses:
        200:
          $ref: "./v1-commons.yaml#/components/responses/Login"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/prescription:
    get:
      summary: "Operation to retrieve a list (max. 50 entries) of e-prescriptions, sorted in descending order by creation date"
      description: "UC: E-Rezepte empfangen
      See https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#alle-e-rezepte-ansehen"
      tags:
        - E-Prescription
        - EU-Prescription
      responses:
        200:
          $ref: "./v1-prescription.yaml#/components/responses/Prescriptions"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/prescription/{id}:
    parameters:
      - name: id
        required: true
        in: path
        schema:
          $ref: "./v1-prescription.yaml#/components/schemas/PrescriptionId"
    get:
      summary: "Operation to download a single e-prescription"
      description: "UC: E-Rezepte empfangen
            See https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#ein-einzelnes-e-rezept-abrufen-und-in-der-apotheke-einl%C3%B6sen"
      tags:
        - E-Prescription
        - EU-Prescription
      responses:
        200:
          $ref: "./v1-prescription.yaml#/components/responses/Prescription"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
    delete:
      summary: "Operation to delete an e-prescription"
      description: "UC: E-Rezepte am E-Rezept Fachdienst löschen See https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#ein-e-rezept-l%C3%B6schen"
      tags:
        - E-Prescription
      responses:
        204:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
    patch:
      summary: "Operation to change an e-prescription. Currently, an e-prescription can be activated for redemption in other European countries."
      description: "In the context of European e-prescriptions, an e-prescription must be activated. This can be controlled via the attribute RedeemableByPatient."
      tags:
        - E-Prescription
        - EU-Prescription
      requestBody:
        $ref: "./v1-eu-prescription.yaml#/components/requestBodies/EU-RedeemableByPatient"
      responses:
        200:
          $ref: "./v1-prescription.yaml#/components/responses/Prescription"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
  /erp/testdriver/api/v1/medicationdispense:
    get:
      summary: "Operation returns a list (max. 50 entries) of medication dispense information's, sorted in descending order by creation date"
      description: "The response contains information on dispenses both in Germany and in other EU countries."
      tags:
        - Dispensing information
        - EU-Prescription
      parameters:
        - name: whenhandedover
          in: query
          schema:
            type: string
            description: "See https://www.hl7.org/fhir/medicationdispense-search.html#MedicationDispense-whenhandedover"
            example: "gt2020-03-01"
      responses:
        200:
          $ref: "./v1-medication-dispense.yaml#/components/responses/MedicationDispenses"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/auditEvents:
    get:
      summary: "Operation returns a list (max. 50 entries) of audit events, sorted in descending order by creation date"
      description: "UC: Protokolldaten anzeigen
      See https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#einsicht-in-das-zugriffsprotokoll"
      tags:
        - Audit Events
      responses:
        200:
          $ref: "./v1-auditevent.yaml#/components/responses/AuditEvents"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/pharmacy/search:
    get:
      summary: "Operation to search for pharmacies based on specific attributes."
      description: "UC: Apotheke suchen
      See https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#eine-apotheke-aus-dem-apotheken-verzeichnis-ausw%C3%A4hlen"
      tags:
        - Pharmacy
      parameters:
        - name: near
          in: query
          schema:
            type: string
            example: "48.13129322109354%7C11.563464055060686%7C999%7Ckm"
        - name: address-city
          in: query
          schema:
            type: string
            example: "Berlin"
        - name: name
          in: query
          schema:
            type: string
            example: "Apotheke%20um%20die%20Ecke"
      responses:
        200:
          $ref: "./v1-healthcare-providers.yaml#/components/responses/Pharmacies"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/pharmacy/assignment:
    post:
      description: "Operation is intended to assign an e-prescription to a pharmacy"
      tags:
        - Pharmacy
      requestBody:
        $ref: "./v1-communication.yaml#/components/requestBodies/PharmacyAssignment"
      responses:
        200:
          $ref: "./v1-communication.yaml#/components/responses/PharmacyAssignment"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/pharmacy/2dCode:
    post:
      description: "Operation generates e-prescription token as 2D code"
      tags:
        - Pharmacy
      requestBody:
        $ref: "./v1-healthcare-providers.yaml#/components/requestBodies/2DCode"
      responses:
        200:
          $ref: "./v1-healthcare-providers.yaml#/components/responses/2DCode"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/communication:
    get:
      summary: "Operation returns a list (max. 50 entries) of communications for a patient, sorted in descending order by creation date"
      description: "UC: Nachrichten von Apotheke anzeigen
        https://github.com/gematik/api-erp/blob/master/docs/erp_communication.adoc#anwendungsfall-alle-nachrichten-vom-e-rezept-fachdienst-abrufen"
      tags:
        - Communication
      responses:
        200:
          $ref: "./v1-communication.yaml#/components/responses/Communications"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/communication/{id}:
    delete:
      summary: "Operation to delete a communication by id"
      description: "UC: Nachrichten löschen
          https://github.com/gematik/api-erp/blob/master/docs/erp_communication.adoc#anwendungsfall-nachricht-als-apotheke-l%C3%B6schen"
      tags:
        - Communication
      parameters:
        - name: id
          required: true
          in: path
          schema:
            $ref: "./v1-communication.yaml#/components/schemas/CommunicationId"
      responses:
        204:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/consent:
    post:
      summary: "Operation to create a consent for a patient by category"
      tags:
        - Consent
        - EU-Prescription
      parameters:
        - in: query
          name: category
          required: true
          schema:
            $ref: "./v1-consent.yaml#/components/schemas/ConsentCategory"
      responses:
        201:
          $ref: "./v1-consent.yaml#/components/responses/Consent"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
        409:
          description: "Consent could not be created due to a conflict"
          content:
            application/json:
              schema:
                $ref: "./v1-commons.yaml#/components/schemas/OperationOutcome"
              examples:
                consentExists:
                  $ref: "./v1-consent.yaml#/components/examples/consentExists"
    delete:
      summary: "Operation to delete a consent for a patient by category"
      tags:
        - Consent
        - EU-Prescription
      parameters:
        - in: query
          name: category
          required: true
          schema:
            $ref: "./v1-consent.yaml#/components/schemas/ConsentCategory"
      responses:
        204:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
    get:
      summary: "Operation to retrieve a consent for a patient by category"
      tags:
        - Consent
        - EU-Prescription
      parameters:
        - in: query
          name: category
          required: true
          schema:
            $ref: "./v1-consent.yaml#/components/schemas/ConsentCategory"
      responses:
        200:
          $ref: "./v1-consent.yaml#/components/responses/Consent"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        404:
          description: "Consent not found for current patient and category"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
  /erp/testdriver/api/v1/eu-access-authorization:
    post:
      summary: "Operation to grant a EU-AccessAuthorization for a country"
      tags:
        - EU-Prescription
      parameters:
        - in: query
          name: country
          required: true
          schema:
            $ref: "./v1-commons.yaml#/components/schemas/CountryIso3166"
        - in: query
          name: accessCode
          description: "The Remote FdV have to generate the access code if no access code was delivered"
          required: false
          schema:
            $ref: "./v1-prescription.yaml#/components/schemas/EU-AccessCode"
      responses:
        201:
          $ref: "./v1-eu-prescription.yaml#/components/responses/EU-AccessAuthorization"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
    delete:
      summary: "Operation to revoke a EU-AccessAuthorization for a patient"
      tags:
        - EU-Prescription
      responses:
        204:
          $ref: "./v1-commons.yaml#/components/responses/Successful"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"
    get:
      summary: "Operation to retrieve a EU-AccessAuthorization for a patient"
      tags:
        - EU-Prescription
      responses:
        200:
          $ref: "./v1-eu-prescription.yaml#/components/responses/EU-AccessAuthorization"
        403:
          $ref: "./v1-commons.yaml#/components/responses/Forbidden"
        400:
          $ref: "./v1-commons.yaml#/components/responses/TestFdVError"

components:
  securitySchemes:
    apiKey:
      type: apiKey
      description: API key to authorize requests.
      name: apiKey
      in: header

security:
  - apiKey: [ ]
